#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Проверяем strict-типы TypeScript по всему проекту
npm run type-check

# Форматируем и линтим только измененные файлы в гит-индексе
npx lint-staged
